(function () {
  function initApp() {
    if (!document.getElementById("projectForm")) { return; }
    const mode = BOQUtils.getMode();
    const state = { user: BOQUtils.storage.get("boq_user", null) || { name: "Guest User", email: "No email saved", projectCount: 0, unlimitedAccess: false }, selectedScopes: Object.keys(BOQ_DATA.scopeLibrary), result: null, unlocked: false };
    const elements = { projectType: document.getElementById("projectType"), country: document.getElementById("country"), projectName: document.getElementById("projectName"), finishLevel: document.getElementById("finishLevel"), floors: document.getElementById("floors"), rooms: document.getElementById("rooms"), length: document.getElementById("length"), width: document.getElementById("width"), height: document.getElementById("height"), basement: document.getElementById("basement"), efficiency: document.getElementById("efficiency"), complexity: document.getElementById("complexity"), gfaOutput: document.getElementById("gfaOutput"), currencyOutput: document.getElementById("currencyOutput"), standardOutput: document.getElementById("standardOutput"), currentUserName: document.getElementById("currentUserName"), currentUserEmail: document.getElementById("currentUserEmail"), currentModeLabel: document.getElementById("currentModeLabel"), currentStandardLabel: document.getElementById("currentStandardLabel"), projectCountValue: document.getElementById("projectCountValue"), projectCountHint: document.getElementById("projectCountHint"), modeSidebarText: document.getElementById("modeSidebarText"), workspaceTitle: document.getElementById("workspaceTitle"), workspaceIntro: document.getElementById("workspaceIntro"), generateButton: document.getElementById("generateButton"), boqHeading: document.getElementById("boqHeading"), costHeading: document.getElementById("costHeading"), boqTableBody: document.getElementById("boqTableBody"), costSummary: document.getElementById("costSummary"), takeoffGrid: document.getElementById("takeoffGrid"), projectNotes: document.getElementById("projectNotes"), scopeGrid: document.getElementById("scopeGrid"), scopeNote: document.getElementById("scopeNote"), uploadZone: document.getElementById("uploadZone"), drawingFile: document.getElementById("drawingFile"), uploadFeedback: document.getElementById("uploadFeedback"), unlockButton: document.getElementById("unlockButton"), accessCode: document.getElementById("accessCode"), unlockMessage: document.getElementById("unlockMessage"), upgradeButton: document.getElementById("upgradeButton"), resetProjectButton: document.getElementById("resetProjectButton"), pdfButton: document.getElementById("pdfButton") };
    function populateSelect(select, collection, selectedKey) { select.innerHTML = Object.keys(collection).map(function (key) { return "<option value='" + key + "'" + (key === selectedKey ? " selected" : "") + ">" + collection[key].label + "</option>"; }).join(""); }
    function renderScopeGrid() {
      elements.scopeGrid.innerHTML = Object.keys(BOQ_DATA.scopeLibrary).map(function (scopeKey) { const scope = BOQ_DATA.scopeLibrary[scopeKey]; const checked = state.selectedScopes.indexOf(scopeKey) >= 0 ? "checked" : ""; return "<label class='scope-option'><input type='checkbox' value='" + scopeKey + "' " + checked + "><span><strong>" + scope.name + "</strong><small>" + scope.descriptions.default + "</small></span></label>"; }).join("");
      elements.scopeGrid.querySelectorAll("input[type='checkbox']").forEach(function (checkbox) { checkbox.addEventListener("change", function () { state.selectedScopes = Array.from(elements.scopeGrid.querySelectorAll("input[type='checkbox']:checked")).map(function (item) { return item.value; }); elements.scopeNote.textContent = state.selectedScopes.length + " scope packages selected"; }); });
    }
    function getInput() { return { mode: mode, projectType: elements.projectType.value, country: elements.country.value, projectName: elements.projectName.value.trim() || "Untitled Project", finishLevel: elements.finishLevel.value, floors: Number(elements.floors.value || 0), rooms: Number(elements.rooms.value || 0), length: Number(elements.length.value || 0), width: Number(elements.width.value || 0), height: Number(elements.height.value || 0), basement: Number(elements.basement.value || 0), efficiency: Number(elements.efficiency.value || 0), complexity: Number(elements.complexity.value || 1) }; }
    function updateMeta() { const input = getInput(); const area = BOQEngine.getArea(input) * (BOQ_DATA.projectTypes[input.projectType].areaFactor || 1); const country = BOQ_DATA.countries[input.country]; elements.gfaOutput.textContent = BOQUtils.formatNumber(area, 0) + " m2"; elements.currencyOutput.textContent = country.currency; elements.standardOutput.textContent = country.standard; elements.currentStandardLabel.textContent = country.standard + " · " + country.currency; }
    function renderSummary(result) {
      elements.boqTableBody.innerHTML = result.items.map(function (item) { return "<tr><td>" + item.itemNumber + "</td><td><strong>" + item.scopeName + "</strong><br><small>" + item.description + "</small></td><td>" + item.unit + "</td><td>" + BOQUtils.formatNumber(item.quantity, 2) + "</td><td>" + BOQUtils.formatCurrency(item.rate, result.country.currency) + "</td><td>" + BOQUtils.formatCurrency(item.amount, result.country.currency) + "</td></tr>"; }).join("");
      elements.costSummary.innerHTML = BOQCost.getCostSummary(result).map(function (row) { return "<div class='summary-row" + (row.emphasis ? " total-row" : "") + "'><span>" + row.label + "</span><strong>" + row.value + "</strong></div>"; }).join("");
      elements.takeoffGrid.innerHTML = [{ label: "Cement Bags", value: result.takeoff.cement + " bags" }, { label: "Reinforcement Steel", value: result.takeoff.steel + " kg" }, { label: "Blocks", value: result.takeoff.blocks + " nos" }, { label: "Tiles / Finish Area", value: result.takeoff.tiles + " m2" }].map(function (item) { return "<div class='takeoff-item'><span>" + item.label + "</span><strong>" + item.value + "</strong></div>"; }).join("");
      const notes = result.notes.slice(); if (result.roiYears) { notes.push("Indicative solar payback period: " + result.roiYears + " years."); }
      elements.projectNotes.innerHTML = notes.map(function (note) { return "<p>" + note + "</p>"; }).join("");
    }
    function updateUsage() { const count = Number(state.user.projectCount || 0); const locked = !state.user.unlimitedAccess && !state.unlocked && count >= 10; elements.projectCountValue.textContent = state.user.unlimitedAccess || state.unlocked ? (count + " / Unlimited") : (count + " / 10"); elements.projectCountHint.textContent = locked ? "Project limit reached" : "Free usage available"; elements.generateButton.disabled = locked; if (locked) { elements.unlockMessage.textContent = "Free project limit reached. Upgrade via WhatsApp or unlock with access code."; } }
    function saveUser() { BOQUtils.storage.set("boq_user", state.user); }
    function renderUserState() {
      elements.currentUserName.textContent = state.user.name || "Guest User"; elements.currentUserEmail.textContent = state.user.email || "No email saved"; elements.currentModeLabel.textContent = mode.toUpperCase(); elements.modeSidebarText.textContent = mode === "boq" ? "Bill of Quantities Workspace" : "Cost Planning Workspace"; elements.workspaceTitle.textContent = mode === "boq" ? "BOQ Mode" : "Cost Mode"; elements.workspaceIntro.textContent = mode === "boq" ? "Detailed quantity breakdown aligned to the selected project type, scope mix, and regional standard." : "Budget-focused commercial estimate with cost per square meter, margin, contingency, and turnkey trade coverage."; elements.generateButton.textContent = mode === "boq" ? "Generate BOQ" : "Generate Cost Estimate"; elements.boqHeading.textContent = mode === "boq" ? "Measured bill of quantities" : "Trade build-up used for cost estimate"; elements.costHeading.textContent = mode === "boq" ? "Commercial summary" : "Budget summary";
    }
    function generate() { updateUsage(); if (elements.generateButton.disabled) { return; } state.result = BOQEngine.generateBoq(getInput(), state.selectedScopes); state.user.projectCount = Number(state.user.projectCount || 0) + 1; saveUser(); renderUserState(); renderSummary(state.result); updateUsage(); }
    function handleUpload(file) { if (!file) { return; } const extraction = BOQCad.simulateExtraction(file.name, elements.projectType.value); elements.floors.value = extraction.fields.floors; elements.rooms.value = extraction.fields.rooms; elements.length.value = extraction.fields.length; elements.width.value = extraction.fields.width; elements.height.value = extraction.fields.height; elements.basement.value = extraction.fields.basement; elements.uploadFeedback.textContent = extraction.message; updateMeta(); }
    function resetProject() { elements.projectName.value = ""; elements.finishLevel.value = "standard"; elements.floors.value = 2; elements.rooms.value = 8; elements.length.value = 7.5; elements.width.value = 6.5; elements.height.value = 3.4; elements.basement.value = 0; elements.efficiency.value = 82; elements.complexity.value = 1; state.selectedScopes = Object.keys(BOQ_DATA.scopeLibrary); renderScopeGrid(); updateMeta(); elements.boqTableBody.innerHTML = ""; elements.costSummary.innerHTML = ""; elements.takeoffGrid.innerHTML = ""; elements.projectNotes.innerHTML = ""; elements.uploadFeedback.textContent = "No drawing analyzed yet."; }
    populateSelect(elements.projectType, BOQ_DATA.projectTypes, "residential"); populateSelect(elements.country, BOQ_DATA.countries, "saudi"); renderScopeGrid(); renderUserState(); updateMeta(); updateUsage(); generate();
    [elements.projectType, elements.country, elements.finishLevel, elements.floors, elements.rooms, elements.length, elements.width, elements.height, elements.basement, elements.efficiency, elements.complexity].forEach(function (element) { element.addEventListener("input", updateMeta); element.addEventListener("change", updateMeta); });
    elements.projectType.addEventListener("change", function () { const preset = BOQCad.getPreset(elements.projectType.value); elements.floors.value = preset.floors; elements.rooms.value = preset.rooms; elements.length.value = preset.length; elements.width.value = preset.width; elements.height.value = preset.height; elements.basement.value = preset.basement; updateMeta(); });
    elements.drawingFile.addEventListener("change", function (event) { handleUpload(event.target.files[0]); });
    ["dragenter", "dragover"].forEach(function (eventName) { elements.uploadZone.addEventListener(eventName, function (event) { event.preventDefault(); elements.uploadZone.classList.add("dragging"); }); });
    ["dragleave", "drop"].forEach(function (eventName) { elements.uploadZone.addEventListener(eventName, function (event) { event.preventDefault(); elements.uploadZone.classList.remove("dragging"); }); });
    elements.uploadZone.addEventListener("drop", function (event) { handleUpload(event.dataTransfer.files[0]); });
    elements.generateButton.addEventListener("click", generate); elements.resetProjectButton.addEventListener("click", resetProject);
    elements.unlockButton.addEventListener("click", function () { const code = elements.accessCode.value.trim(); if (BOQ_DATA.accessCodes[code]) { state.unlocked = true; state.user.unlimitedAccess = true; saveUser(); elements.unlockMessage.textContent = "Access unlocked: " + BOQ_DATA.accessCodes[code].label; updateUsage(); } else { elements.unlockMessage.textContent = "Invalid access code."; } });
    elements.upgradeButton.addEventListener("click", function () { const message = encodeURIComponent("Hello, I want to upgrade BOQ Pro for unlimited project estimation access."); window.open("https://wa.me/966511759092?text=" + message, "_blank"); });
    elements.pdfButton.addEventListener("click", function () { if (!state.result) { generate(); } if (state.result) { BOQPdf.exportReport({ mode: mode, projectName: elements.projectName.value.trim() || "Untitled Project", result: state.result }); } });
  }
  window.BOQApp = { initApp };
  document.addEventListener("DOMContentLoaded", initApp);
})();
